FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# PingPov Api

Polls is a simple API allowing consumers to view polls and vote in them.

## Prenotazioni Tavolo [/Prenotazioni_Tavolo]

### /prenotaioni [GET]
/prenotazioni serve per ricercare all'interno del database tutti i possibili slot di prenotazione che vengono visualizzati in ordine temporale a partire dalla data e ora selezionate e inoltre filtra anche per la sede
 
+ Response 200 (application/json)

        [
            {
                "prenotazioni":[
                    {"_id":{"$oid":"62825720c87c317dbcb1579f"},
                    "prenotatore":" Pippomarco",
                    "sede":"Povo1"
                    ,"giorno":{"$date":{"$numberLong":"1652662800000"}
                    }
                    },
                    {
                "prenotazioni": [
                    {"_id":{"$oid":"62825745c87c317dbcb1579f"},
                    "prenotatore":"",
                    "sede":"Povo1"
                    ,"giorno":{"$date":{"$numberLong":"1652662800000"}
                    }
                    }
                  
           
        ]
        
        
        
        
        
        
        
### /aggiungiPrenotazione/:id [PUT]
/aggiungiPrenotazione/:id va a cercare all'interno del database la prenotazione con l'id che arriva dalla richiesta, quindi aggiorna il campo "prenotatore" con il nome dell'utente che ha effettuato la richiesta

 + Response 200 ()



### /aggiungiPrenotazione/:id [DELETE]
/aggiungiPrenotazione/:id va a cercare all'interno del database la prenotazione con l'id che arriva dalla richiesta, quindi aggiorna il campo "prenotatore" con la stringa vuota, che rappresenta una prenotazione non effettuata
nel caso in cui l'utente che effettui la richiesta non sia lo stesso che ha precedentemente effettuato la prenotazione, gli viene inviato un messaggio di errore.

 + Response 200 ()